# Generated by Django 4.2.16 on 2026-04-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('lostfound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangchat',
            name='laporan',
            field=models.ForeignKey(blank=True, help_text='Opsional: chat terkait laporan barang tertentu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruang_chat', to='lostfound.laporanbarang'),
        ),
        migrations.AddField(
            model_name='ruangchat',
            name='peserta',
            field=models.ManyToManyField(related_name='ruang_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesan',
            name='pengirim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_terkirim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesan',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='chat.ruangchat'),
        ),
    ]
