# Generated by Django 4.2.16 on 2026-04-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nim_nik', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('staf', 'Staf Kampus'), ('security', 'Petugas Keamanan'), ('admin', 'Administrator')], default='mahasiswa', max_length=20)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
            },
        ),
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('ikon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Barang',
            },
        ),
        migrations.CreateModel(
            name='LaporanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('hilang', 'Barang Hilang'), ('temuan', 'Barang Temuan')], max_length=10)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('tanggal_kejadian', models.DateField()),
                ('kontak_wa', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('proses', 'Dalam Proses Klaim'), ('diambil', 'Barang Telah Diambil')], default='aktif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan', to='lostfound.kategoribarang')),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(choices=[('klaim_masuk', 'Ada klaim baru untuk laporan Anda'), ('klaim_disetujui', 'Klaim Anda disetujui'), ('klaim_ditolak', 'Klaim Anda ditolak'), ('pesan_baru', 'Pesan baru dari pengguna lain'), ('info', 'Informasi umum')], default='info', max_length=25)),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lostfound.laporanbarang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='barang/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='lostfound.laporanbarang')),
            ],
        ),
        migrations.CreateModel(
            name='KlaimBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_ktm', models.ImageField(help_text='Foto KTM/KTP sebagai bukti identitas', upload_to='ktm/%Y/%m/')),
                ('keterangan', models.TextField(blank=True, help_text='Jelaskan ciri khas barang untuk verifikasi')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15)),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan dari admin/pelapor saat approve/tolak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klaim', to='lostfound.laporanbarang')),
                ('pengklaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klaim_saya', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('laporan', 'pengklaim')},
            },
        ),
    ]
